name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master 

    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11

    - name: Install dependencies (if needed)
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Python Script
      run: python3 Educational_SRC_Member_Retrieval.py

    - name: list files
      run: |
        pwd
        ls -l

    - name: Upload Results
      uses: actions/upload-artifact@master
      with:
        name: script-results 
        path: ./*.json
